"""create core schema

Revision ID: 7c7e6ef4fe97
Revises: 
Create Date: 2026-09-23 11:11:01.128796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7e6ef4fe97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('drug_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.Column('last_restocked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('low_stock_threshold >= 0', name='ck_inventory_low_stock_threshold_non_negative'),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_inventory_quantity_non_negative'),
    sa.CheckConstraint('reorder_threshold <= low_stock_threshold', name='ck_inventory_reorder_le_low_stock'),
    sa.CheckConstraint('reorder_threshold >= 0', name='ck_inventory_reorder_threshold_non_negative'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'WAITING_FOR_STOCK', 'DISPENSED', 'COMPLETED', 'CANCELLED', name='orderstatus', native_enum=False, length=30), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_patient_id'), 'orders', ['patient_id'], unique=False)
    op.create_index('ix_orders_status_created_at', 'orders', ['status', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('drug_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WAITING_FOR_STOCK', 'DISPENSED', 'CANCELLED', name='orderitemstatus', native_enum=False, length=30), nullable=False),
    sa.Column('dispensed_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dispensed_quantity >= 0', name='ck_order_items_dispensed_quantity_non_negative'),
    sa.CheckConstraint('requested_quantity > 0', name='ck_order_items_requested_quantity_positive'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'drug_id', name='uq_order_items_order_drug')
    )
    op.create_index('ix_order_items_drug_status', 'order_items', ['drug_id', 'status'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('drug_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('order_item_id', sa.BigInteger(), nullable=True),
    sa.Column('movement_type', sa.Enum('RESTOCK', 'DISPENSE', 'ADJUSTMENT', name='inventorymovementtype', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.Enum('NEW_ORDER', 'PENDING_FULFILMENT', 'MANUAL_RESTOCK', 'MANUAL_ADJUSTMENT', name='inventorymovementsource', native_enum=False, length=30), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_transactions_drug_created_at', 'inventory_transactions', ['drug_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_drug_id'), 'inventory_transactions', ['drug_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_order_id'), 'inventory_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_order_item_id'), 'inventory_transactions', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_order_item_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_order_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_drug_id'), table_name='inventory_transactions')
    op.drop_index('ix_inventory_transactions_drug_created_at', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index('ix_order_items_drug_status', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_status_created_at', table_name='orders')
    op.drop_index(op.f('ix_orders_patient_id'), table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_table('inventory')
    op.drop_table('patients')
    op.drop_table('drugs')
    # ### end Alembic commands ###
